
mode: "test"

exp_prefix: "pretrained_forecaster"

base_dir: "results/{{exp_prefix}}"
data_dir: "data"
object_dir: "{{data_dir}}/object_type_20.json"

log_dir: "log.jsonl"
checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: 18000

framework:
    seed: 0
    num_thread: 4
    num_gpu: 1
    batch_size: 128
    buffer_size: 512

thor:
    restart_cond: 50
    port: 7700
    x_display_offset: 0
    time_scale: 1
    delta_time: 0.02
    max_time: 50

agent:
    protocol: VA
    protocol_model: PM
    protocol_actor:
    forecaster:
        train: False
    actor:
        train: False
        gamma: 0.99
        beta: 0.5
    ND: 3
    PScale: 0.01
    CD: 21
    NSample: 100000
    Horizon: 3
    DScale: 0.05
    hidden_size: 256
    height_difference: 0.44
    gt_camera_pose: False
    noise_sigma: 0.0

train:
    meta: "{{data_dir}}/train.json"
    num_epoch: 1
    lr_f: 0.1
    lr_f_ms: [15000, 20000]
    lr_a: 0.0001
    random_object: False
    save_iter: 1000

val:
    meta: "{{data_dir}}/val.json"
    random_object: False

test:
    meta: "{{data_dir}}/test.json"
    random_object: False
